#!/usr/bin/env ruby

require 'yaml'

POSTS_DIR = '_posts/'
TAGS_DIR = 'tags/'

Dir.foreach(POSTS_DIR) do |post|
  next if ['.', '..', '.DS_Store'].include?(post)

  postYaml = YAML.load_file(POSTS_DIR + post)
  unless postYaml['tags'].nil?
    postYaml['tags'].each do |tag|
      tag.downcase!

      next if File.exist?(TAGS_DIR + tag + '.html')

      puts('[+] Generating #' + tag + ' page')

      File.open(TAGS_DIR + tag + '.html', 'w') do |f|
        f.write(
          "---\nlayout: tag\nsection-type: tag\ntitle: " + tag + "\n---\n## Tag"
        )
      end
    end
  end
end
