#!/usr/bin/env ruby

require 'yaml'

POSTS_DIR = '_posts/'
CATEGORIES_DIR = 'categories/'

# This function will create an html file for a category if it doesn't exist already
def create_category(category)

    unless File.exist?(CATEGORIES_DIR + category.downcase + '.html')
      puts('[+] Generating #' + category + ' page')
      File.open(CATEGORIES_DIR + category.downcase + '.html', 'w') {|f| f.write(
      "---\nlayout: category\nsection-type: category\ntitle: " + category + "\n---\n## Category")}
    end

end

Dir.foreach(POSTS_DIR) do |post|

  next if post == '.' or post == '..' or post == '.DS_Store'
  postYaml = YAML.load_file(POSTS_DIR + post)

  # Checks if there is a unique category
  unless (postYaml['category'] == nil)
    category = postYaml['category']
    create_category(category)
  end
  
  # Checks if there are several categories
  unless (postYaml['categories'] == nil)
    postYaml['categories'].each {|category| create_category(category)}
  end

end
